<?php

namespace App\Filament\Pages\Auth;

use Filament\Auth\Pages\Login as BasePage;
use Filament\Forms\Components\Select;
use Filament\Schemas\Schema;

class Login extends BasePage
{
    public function mount(): void
    {
        parent::mount();

        if (app()->environment('local')) {
            $this->form->fill([
                'email' => 'test@filamentphp.com',
                'password' => 'password',
                'remember' => true,
            ]);
        }
    }

    public function form(Schema $schema): Schema
    {
        $options = [
            'One' => 'One',
            'two' => 'Two',
            'three' => 'Three',
            'four' => 'Four',
            'five' => 'Five',
        ];
        return parent::form($schema)->schema([
            Select::make('test')
                ->searchable()
                ->getSearchResultsUsing(
                    fn ($search) => array_filter($options, fn ($label) => str_contains($label, $search))
                )
        ]); // TODO: Change the autogenerated stub
    }
}
